# Generated by Django 5.2 on 2025-05-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images'),
        ),
    ]
